- android/1_download_library.sh
- android/2_build_toolchain.sh
- android/3_build_liblcf.sh
- android/4_build_android_port.sh
- android/README
I just adapted some command such as ant (because Android Studio use Gradle) and some path.
I'm currently testing that from scratch :)
> Migrate to gradle

- android/3_build_liblcf.sh
This git pull is usefull if the script is not executed for the first time (in case of modification).
> Android : git pull in liblcf folder before building

- 3ds/1_download_library.sh
- 3ds/2_build_toolchain.sh
- 3ds/3_cleanup.sh
- 3ds/libsndfile.patch
- android/1_download_library.sh
- android/2_build_toolchain.sh
- wii/1_download_library.sh
- wii/2_build_toolchain.sh
- wii/3_cleanup.sh
- wii/libiconv.patch
- wii/libsndfile.patch
> Android, Wii & 3DS: And libsndfile and speexdsp. Update libpng to 1.6.23

- android/1_download_library.sh
(Recompiling on the server is not needed, I already installed the packages there)
> Android: Add API23 and Android support library

- android/1_download_library.sh
- vita/1_download_library.sh
- vita/2_build_toolchain.sh
- vita/3_cleanup.sh
> Update Vita Toolchain and add Android API 24

- android/1_download_library.sh
- android/2_build_toolchain.sh
- wii/1_download_library.sh
- wii/2_build_toolchain.sh
- wii/3_cleanup.sh
> Add libxmp, replace libmodplug

- android/1_download_library.sh
- android/2_build_toolchain.sh
- android/xmplite-android.patch
* the SDL change is untested, but *should* work.
> Fix Android port building

- android/1_download_library.sh
- android/2_build_toolchain.sh
- android/4_build_android_port.sh
I'm not able to test this PR (poor internet connection) but it should be well :).
> [Android] Get back to Android SDK 23

- 3ds/2_build_toolchain.sh
- android/1_download_library.sh
- android/2_build_toolchain.sh
- android/README.md
- vita/2_build_toolchain.sh
- wii/2_build_toolchain.sh
Do not have time to polish my updates branch fully before 0.5.2, so cherry picking some stuff separately.
Each part should be easy to review.
> Increase patching portability (on OSX)

- windows/build-icu.cmd
- windows/build.cmd
By using a wildcard-copy.
And setting correct PLATFORM and EASYDEV_MSVC defaults to prevent problems as in #19
> MSVC: Select correct ICU datafile

- linux-static/0_build_everything.sh
- linux-static/1_download_library.sh
- linux-static/2_build_toolchain.sh
- linux-static/3_cleanup.sh
- linux-static/README.md
- linux-static/libxmp-a0288352.patch
(all libraries updated.)
EDIT: Have compiled all linux jobs on jenkins with this now, no problems.
> Add Linux buildscript

- emscripten/0_build_everything.sh
- emscripten/1_download_library.sh
- emscripten/2_build_toolchain.sh
- emscripten/3_cleanup.sh
- emscripten/libsndfile.patch
- emscripten/libxmp-a0288352.patch
> Add Emscripten toolchain

- android/1_download_library.sh
- android/2_build_toolchain.sh
> Update android libraries

- android/1_download_library.sh
- android/2_build_toolchain.sh
- android/4_build_liblcf.sh
- android/5_build_android_port.sh
Bump SDK Version to 28
Tested and works.
> Bump Android SDK Version

- android/5_build_android_port.sh
> Fix tool path

- 3ds/1_download_library.sh
- 3ds/2_build_toolchain.sh
- 3ds/3_cleanup.sh
- 3ds/README.md
- switch/1_download_library.sh
- switch/2_build_toolchain.sh
- switch/README.md
- wii/1_download_library.sh
- wii/2_build_toolchain.sh
- wii/3_cleanup.sh
- wii/README.md
- wii/icu-wii.patch
- wii/packages.sh
- wii/sdl-wii.patch
3ds: Enable Opus support
wii: Enable optimizations
Resolves #38.
> 3ds/wii/switch: Let the user take care of devkitXXX

- 3ds/2_build_toolchain.sh
- shared/extra/pixman-simd.patch
- switch/2_build_toolchain.sh
- vita/2_build_toolchain.sh
> Enable Pixman SIMD for 3ds, Switch and PS Vita

- ios/2_build_toolchain.sh
- osx/2_build_toolchain.sh
Didn't forget the patches: Got the paths to the patches wrong :/
> macos & ios: Fix patch path

- .gitignore
- windows/build.cmd
- windows/icu-easyrpg/CONTROL
- windows/icu-easyrpg/fix-extra.patch
- windows/icu-easyrpg/fix_parallel_build_on_windows.patch
- windows/icu-easyrpg/portfile.cmake
- windows/icu-easyrpg/remove-MD-from-configure.patch
Reapplied our ICU 61 patch to ICU 65.
Fix #65
> Windows: Update ICU to 65.1

- emscripten/1_download_library.sh
- emscripten/2_build_toolchain.sh
Also allow the user to use a preinstalled emscripten.
> Fix Emscripten build

- README.md
- android/1_download_library.sh
- shared/common.sh
- vita/1_download_library.sh
Reduce frustration because of unreachable hosts.
> Mirror dependencies on easyrpg.org

- shared/common.sh
> Replace WORKSPACE with PLATFORM_PREFIX for libmpg123 to fix Android

- windows/build.cmd
Untested.
Waiting for feedback from https://community.easyrpg.org/t/strange-midi-sound-after-building-player-on-windows/864
> VCPKG: Enable nativemidi for SDL2 mixer

- android/4_build_liblcf.sh
> Fix DHB_NO_MMAP in 4_build_liblcf.sh

- shared/packages.sh
> Bump FluidLite to latest commit (fixes drums)

- emscripten/1_download_library.sh
> Update emscripten to 2.0.1

- windows/README.md
- windows/build.cmd
- windows/build_qt5.cmd
- windows/helper/prepare.cmd
> Windows: Add qt5 build script

- windows/icu-easyrpg/portfile.cmake
> Fix icudata file hash (after adding the ICU68 datafile)

- vita/1_download_library.sh
- vita/2_build_toolchain.sh
> Bump vitasdk to v1455

- emscripten/1_download_library.sh
> Emscripen: Bump to 2.0.20

- vita/2_build_toolchain.sh
- vita/vitasdk-cmake.patch
Needed for EasyRPG/Player#2602.
> psvita: Allow the cmake toolchain finding libfmt

- LICENSE
- android/1_download_library.sh
- android/2_build_toolchain.sh
- emscripten/1_download_library.sh
- emscripten/2_build_toolchain.sh
- emscripten/fluidsynth-emscripten.patch
- linux-static/1_download_library.sh
- linux-static/2_build_toolchain.sh
- osx/1_download_library.sh
- osx/2_build_toolchain.sh
- shared/common.sh
- shared/fluidsynth-no-glib.patch
- shared/packages.sh
- switch/1_download_library.sh
- switch/2_build_toolchain.sh
- windows/build.cmd
- windows/fluidsynth-easyrpg/fluidsynth-no-glib.patch
- windows/fluidsynth-easyrpg/force-x86-gentables.patch
- windows/fluidsynth-easyrpg/portfile.cmake
- windows/fluidsynth-easyrpg/vcpkg.json
- windows/helper/prepare.cmd
marked as WIP because this needs compile tests and runtime tests, this is experimental
> Add Fluidsynth without glib dependency

- android/2_build_toolchain.sh
- emscripten/1_download_library.sh
- emscripten/2_build_toolchain.sh
- emscripten/sdl2-fix-timer.patch
- osx/2_build_toolchain.sh
- shared/common.sh
- shared/packages.sh
SDL2: Bump to 2.0.20. Emscripten uses now upstream SDL2
> Emscripten: Bump to 3.1.4

- emscripten/1_download_library.sh
- emscripten/2_build_toolchain.sh
- shared/common.sh
- shared/packages.sh
Just freetype. Harfbuzz is not worth it right now and it makes the Player ever larger
> Emscripten: Update and enable Freetype

- shared/common.sh
> cleanup: Delete lhasa and inih folders

- shared/mk-meson-cross.sh
- vita/1_download_library.sh
A gift by GNOME that keeps on giving...
(yes I built Player locally to test this)
> Vita: Disable PIC in meson

- windows/build_tools.cmd
> FreeImage (vcpkg): Requires libwebpmux to build
