EasyRPG/buildscripts

ios/0_build_everything.sh
ios/1_download_library.sh
ios/2_build_toolchain.sh
ios/3_cleanup.sh
ios/README.md
ios/libxmp-a0288352.patch
osx/0_build_everything.sh
osx/1_download_library.sh
osx/2_build_toolchain.sh
osx/3_cleanup.sh
osx/README.md
osx/SDL2_mixer.patch
osx/expat-2.2.1-osx.patch
osx/libxmp-a0288352.patch

Requires MacOSX, no osxcross support
This PR is mostly for discussion. The build_easyrpg.sh is just a reference for Jenkins, will remove it later.
The toolchains are already placed where the Jenkins job would put them ($JENKINS/ios-toolchain/ios and $JENKINS/osx-toolchain/osx) for playing around.

Add buildscript for MacOSX and iOS

---

shared/extra/mpg123.patch
switch/2_build_toolchain.sh

(different definition used in mpg123 vs. wildmidi upstream patch)

Fix switch toolchain

---

windows/build.cmd
windows/icu-easyrpg/fix_parallel_build_on_windows.patch
windows/icu-easyrpg/portfile.cmake

Upstream vcpkg is still on 61.1 but they changed how the extract command works.
Updated to the portfile from latest vcpkg and fixed extract location for our custom data file.
Confirmed working already on the buildbot.

Windows: Update ICU patch to latest version

---

android/1_download_library.sh
android/2_build_toolchain.sh
android/4_build_liblcf.sh
shared/packages.sh

SDL library updates.
The new SDK runs with Java 13 (old one failed already on Java 9). Though the gradle wrapper we bundle with Player is still Java 8 only.
Lets hope that the "6200805_latest.zip" URL stays valid and that they dont drop "latest" when there is a new release ^^'.

Android: Update to latest SDK installer. Drop armeabi, add x86_64

---

windows/build.cmd

Freetype learned feature selection a while ago, so we can get rid of bzip2 :)

Vcpkg:  Add Freetype[core]. Prevents the build of bzip2.

---

3ds/2_build_toolchain.sh
android/2_build_toolchain.sh
ios/2_build_toolchain.sh
ios/libogg-fix-typedefs.patch
osx/2_build_toolchain.sh
osx/libogg-fix-typedefs.patch
shared/common.sh
shared/extra/harfbuzz-climits.patch
shared/harfbuzz-pkgconfig.patch
shared/harfbuzz.patch
shared/packages.sh
switch/2_build_toolchain.sh
vita/2_build_toolchain.sh
wii/2_build_toolchain.sh

Player build success status:
Library building only (because we have no up-to-date CMake invocation for this)

Update all libs except ICU

---

emscripten/packages.sh
shared/packages.sh
wii/packages.sh

Use latest maintenance releases, as older ones are not hosted anymore.
ICU site does not host them anymore since some days.

Update ICU download links

---

linux-static/2_build_toolchain.sh

Guess that's a bit of a hack :)
SDL2 semi-ignores PKG_CONFIG_LIBDIR because it supports dynamic loading. It scans the file system for library files directly by asking gcc for default directories..............
E.g. when alsa-dev is installed on the host SDL2 will always enable dynamic loading of Alsa.
Same trick can be used / abused to get pulseaudio (dynamic) on, just need to pass a pkg-config check. Only the header is needed (is in /usr/include). The library is never used.
```
Audio drivers   : disk dummy oss alsa(dynamic) pulse(dynamic)
```
Proof that the libs are dynamic. No dependencies on them.
```
objdump -r libSDL2.a | grep "pulse"
SDL_pulseaudio.o:     file format elf64-x86-64
000000000000000a R_X86_64_PC32     .bss.pulseaudio_handle-0x0000000000000004
[...]
000000000000003c …
```

Linux: Convince SDL2 to enable dynamic pulseaudio library

---

vita/1_download_library.sh

According to henkaku discord vitasdk is not being actively developed anymore and the last SDK is broken...
I pinned for now the previous version that is known to work. Did a Player build to verify this. Is from March 2020 so not that bad.

Vita: Pin vitasdk to 2020-03-07_21-07-07. Last known good version.

---

osx/2_build_toolchain.sh

macos has no ``/usr/include`` anymore.
I fix iOS later. Is not high priority ^^

Fix macos build on Catalina

---

linux-static/2_build_toolchain.sh
shared/common.sh
shared/libxmp-no-symver.patch

macOS enforces position independent code (tested this) and on Android the NDK seems to enforce fPIC already. At least we have no relocation errors on Android (we have multiple .so files there).

Linux: Enable fpic

---

LICENSE
emscripten/1_download_library.sh
emscripten/2_build_toolchain.sh
linux-static/1_download_library.sh
linux-static/2_build_toolchain.sh
osx/1_download_library.sh
osx/2_build_toolchain.sh
shared/add_lib.sh
shared/packages.sh
windows/build.cmd

Fix #87
Emscripten could be useful when tools are ported to the web.
Also added a small, ugly script which injects new lines into the 1 and 2 bash scripts.

Add nlohmann-json for Linux, macOS, Windows and emscripten

---

android/1_download_library.sh

Also removed API 12. I don't think we need this anymore.

Android: Install Android SDK 29

---

vita/0_build_everything.sh
vita/1_download_library.sh
vita/2_build_toolchain.sh
vita/3_cleanup.sh
vita/README.md

Allows us to build liblcf and Player(soon) with cmake.
liblcf:
```console
export VITASDK=../buildscripts/vita/vitasdk
cmake -B build-vita . -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake -DLIBLCF_WITH_XML=OFF -DLIBLCF_ENABLE_TOOLS=OFF
cmake --build build-vita
```

Revamp the vita toolchain

---

osx/2_build_toolchain.sh

Otherwise CMake will use the host version by default

macOS: Set Deployment target to 10.9

---

vita/1_download_library.sh
vita/2_build_toolchain.sh
vita/3_cleanup.sh
vita/libvita2d-no-jpeg.patch

The new make line for libvita2d fixes a crash
The fbo stuff is only used for shaders.
I'm removing all the shader code. Nobody wants to maintain this.

Bump vitasdk and use upstream libvita2d

---

windows/build.cmd

That's the fix I manually applied on the buildbot so it should work.

Freetype (vcpkg): Link to external zlib to fix linking errors

---

shared/common.sh
shared/libsndfile-subst-external-libs.patch
shared/packages.sh

Bump libpng to 1.6.38
---------
Already applied the libsndfile fix manually to unbreak the build

Fix libsndfile static linking

---

shared/packages.sh

These releases fix a CVE
Fix #133 
Only tested on Linux but zlib and expat are usually safe :thinking:

Bump zlib to 1.2.13 and expat to 2.4.9

---

shared/common.sh

Some CMake modules fail when the executables in the folder are deleted

Do not delete bin/ folder anymore

---

3ds/2_build_toolchain.sh
shared/extra/opusfile-devkit.patch
switch/2_build_toolchain.sh

broken here: https://github.com/devkitPro/newlib/commit/68781b6d72c7dead3d65009cb18ccdfe86bc76db
Reason is c89 does not know inline, so using a GCC extension: https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/Alternate-Keywords.html
---
~~Commit untested, as usual.~~ tested for 3DS toolchain.

Fix opusfile compilation in c89 mode

---

macos/2_build_toolchain.sh
shared/common.sh

We know this problem from other systems making fixing this easy
Thanks to brianum (admin of https://vampiresdawn.org fanpage) for reporting.
-----
Already replaced the 0.8 release with a working version.

Fix icudata not working in macOS universal binary

---

shared/packages.sh

This saves us the forced update once the version changes.
Alternatively they provide a github mirror nowadays:
https://github.com/madler/zlib/releases/download/v1.3/zlib-1.3.tar.gz
Build checks done with 3DS, Switch, Wii toolchain.

Update zlib version and use more future proof URL

---

3ds/1_download_library.sh
3ds/2_build_toolchain.sh
LICENSE
android/1_download_library.sh
android/2_build_toolchain.sh
emscripten/1_download_library.sh
emscripten/2_build_toolchain.sh
emscripten/meson-cross.txt
ios/1_download_library.sh
ios/2_build_toolchain.sh
linux-static/1_download_library.sh
linux-static/2_build_toolchain.sh
macos/1_download_library.sh
macos/2_build_toolchain.sh
macos/inih-std11.patch
shared/add_lib.sh
shared/common.sh
shared/extra/lhasa.patch
shared/packages.sh
switch/1_download_library.sh
switch/2_build_toolchain.sh
vita/1_download_library.sh
vita/2_build_toolchain.sh
wii/1_download_library.sh
wii/2_build_toolchain.sh
windows/build.cmd

inih is to get rid of vendoring in liblcf (alternative is using a different ini library).
lhasa is for https://github.com/EasyRPG/Player/pull/3033
Already tested the library on Linux and Windows.
vcpkg package submitted: https://github.com/microsoft/vcpkg/pull/32793
-----
had to add meson here. The "/dev/null" hack appears to work except for emscripten.
not tested on macOS yet

Add inih and lhasa

---

.github/dependabot.yml
.github/workflows/update_libraries.yml
.gitignore
shared/ini2sh.py
shared/packages.ini
shared/packages.sh
shared/updater.py

- ini for library definitions, makes scripting easier
- updater script using anitya, automatically run by github actions every week
- Uses a supercharged ini format with replacements
- adding libraries to/updating `packages.sh` is easier
- no more missed library updates
- will open a pull request for each bunch, can stay open until issues are resolved
- parallel updates (in other PRs) will be recognized once applied
- no functional change for existing scripts
- Automated PR builders on jenkins, to find breakage
https://github.com/carstene1ns/easyrpg-buildscripts/pull/2
(I have pushed an update to harfbuzz and freetype to master branch, these have been removed)

Feature: automatic library updates

---

shared/common.sh
shared/downloader.py

This will help saving some traffic on the server, since most of the libraries are shared between all platforms. The builders delete all files when done.
The provided script can clean the cache directory. (intended to be run by jenkins once a month and after updates)
(The `ini` file is the same as in the other PR and can be deleted after merging any of them.)

Allow caching of downloaded libraries

---

shared/common.sh

meson: Force "lib" as install dir for libraries

---

3ds/2_build_toolchain.sh
android/2_build_toolchain.sh
emscripten/1_download_library.sh
ios/2_build_toolchain.sh
macos/2_build_toolchain.sh
switch/2_build_toolchain.sh
vita/2_build_toolchain.sh

Otherwise gives linker errors for missing neon functions
I have no idea why this is suddenly broken. Only tested on "Switch". Hope this fixes it for all of them as the error is the same on all arm64 targets.
---
EDIT: Does not work for Android and macOS.

Set arm64 explicitly for libpng

---

.github/workflows/stable-compilation.yml
linux-static/1_download_library.sh
linux-static/2_build_toolchain.sh
macos/1_download_library.sh
macos/2_build_toolchain.sh
shared/packages.ini
shared/packages.sh
windows/build.cmd
windows/build_tools.cmd

The vcpkg library uses additional patches and has more dependencies. We need to check how much weight this adds and could run our own later.

Add freeimage and workflow

---

3ds/2_build_toolchain.sh
3ds/icu-3ds-no-mutex.patch

Same issue as on the Wii with broken std::mutex implementation.
We only use ICU from a single thread.
A better patch should implement it with mutexes provided by ctrulib

3DS: Disable Mutex code in ICU because it crashes

---

emscripten/2_build_toolchain.sh
emscripten/pixman-wasm.patch

SSE2 chosen based on discussions from #143
Also updates the patch to use the new meson build file

Emscripten: Adjust Pixman SIMD patch, default to SSE2

---

shared/fluidsynth-no-deps.patch
shared/fluidsynth-no-glib.patch
wii/2_build_toolchain.sh

Lite was tested on Wii
Synth was tested on WiiU

Fluid(Synth|Lite): Big endian fixes

---

shared/fluidsynth-no-deps.patch
shared/fluidsynth-no-glib.patch
shared/packages.ini
shared/packages.sh
windows/fluidsynth-easyrpg/fluidsynth-no-deps.patch
windows/fluidsynth-easyrpg/fluidsynth-no-glib.patch
windows/fluidsynth-easyrpg/portfile.cmake
windows/fluidsynth-easyrpg/vcpkg.json
windows/icu-easyrpg/cleanup_msvc.patch
windows/icu-easyrpg/mingw-strict-ansi.diff
windows/icu-easyrpg/portfile.cmake
windows/icu-easyrpg/vcpkg.json

- Migrated ICU to latest portfile (which is still pretty old though...)
- Bumped fluidsynth to 2.4.3 (including the patch for the other platforms as they share the same no-glib patch)
No further updates planned here, too annoying to do from Windows xD

Windows: Update fluidsynth and ICU

---

shared/libpng-custom-cc.patch
shared/packages.ini
shared/packages.sh
vita/2_build_toolchain.sh

Same issue as for 3DS and Wii
----
After a rebuild we can rerelease the Vita 0.8 VPK :)

Vita: Disable ICU mutex code (deadlocks on startup), bump libpng

---

ios/2_build_toolchain.sh
macos/2_build_toolchain.sh
tvos/2_build_toolchain.sh

Fixes the build as the framework is not merged into a universal binary (we only use the standalone a files)

Apple systems: Disable libpng framework
